The following ABNF grammar defines the Core BIOS protocols:

    bios_proto      = *( METRIC | ALERT )

    ;  No description                                                        

    METRIC          = signature %d1 aux type element_src value unit time
    signature       = %xAA %xA0             ; two octets
    aux             = hash                  ; 
    type            = string                ; Type of metric send (temperature, humidity, power.load, ...)
    element_src     = string                ; Name of source element to which metrics are bind to.
    value           = string                ; Value of metric as plain string
    unit            = string                ; Unit of metric (C, F or K for temperature)
    time            = number-8              ; Metric date/time, -1 will be replaced by actual time on receiving side.

    ;  No description                                                        

    ALERT           = signature %d2 aux rule element_src state severity description time action
    aux             = hash                  ; 
    rule            = string                ; a rule name, that triggers this alert
    element_src     = string                ; name of the element, where alert was detected. Most of the time is would be asset element name
    state           = string                ; state of the alert. Possible values are ACTIVE/ACK-WIP/ACK-IGNORE/ACK-PAUSE/ACK-SILENCE/RESOLVED
    severity        = string                ; severity of the alert. Possible values are INFO/WARNING/CRITICAL
    description     = string                ; a description of the alert
    time            = number-8              ; ALERT date/time, -1 will be replaced by actual time on receiving side by current time.
    action          = string                ; list of strings separated by "/" ( EMAIL/SMS ) ( is optional and can be empty )

    ; A list of name/value pairs
    hash            = hash-count *( hash-name hash-value )
    hash-count      = number-4
    hash-value      = longstr
    hash-name       = string

    ; Strings are always length + text contents
    string          = number-1 *VCHAR
    longstr         = number-4 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-4        = 4OCTET
    number-8        = 8OCTET
