The following ABNF grammar defines the Core FTY protocols:

    fty_proto       = *( METRIC | ALERT | ASSET )

    ;  No description                                                        

    METRIC          = signature %d1 aux time ttl type name value unit
    signature       = %xAA %xA1             ; two octets
    aux             = hash                  ; 
    time            = number-8              ; Metric timestamp -
       unixtime.
    ttl             = number-4              ; Time to live in seconds.

Value defines duration of validity (i.e. how long is metric valid,
when it expires) as well as the latest time we should receive metric
updates.
    type            = string                ; Metric name, e.g.: "temperature", "humidity", "power.load", ...
    name            = string                ; Name of asset where metric is produced.
    value           = string                ; Metric value, e.g.: "25.323" or "900".
    unit            = string                ; Metric unit, e.g.: "C" or "F" for temperature.

    ;  No description                                                        

    ALERT           = signature %d2 aux time ttl rule name state severity description action
    aux             = hash                  ; 
    time            = number-8              ; Alert timestamp - unixtime.
    ttl             = number-4              ; Time to live in seconds.

Value defines duration of validity (i.e. how long is alert valid, when
it expires).
When current unixtime is greater than time + ttl this alert expired
and is no longer valid.
    rule            = string                ; Name of the rule which triggers this alert.
    name            = string                ; Name of asset where alert is trigged.
    state           = string                ; Alert state.

Permissible values:
ACTIVE / ACK-WIP / ACK-IGNORE / ACK-PAUSE / ACK-SILENCE / RESOLVED
    severity        = string                ; Alert severity.

Permissible values:
INFO / WARNING / CRITICAL
    description     = string                ; Alert description.
    action          = string                ; List of slash-separated ('/') actions, e.g.: "EMAIL/SMS".
Can be empty.

    ;  No description                                                        

    ASSET           = signature %d3 aux name operation ext
    aux             = hash                  ; 
    name            = string                ; Asset name.
    operation       = string                ; Asset operation.

Permissible values:
create / update / delete / inventory / retire

A little explanation. Due to historical reasons:
* 'update' is actually 'delete' + 'create', so only it is essentially
   a 'replace' operation: only data passed in this message become the
   new content of asset information.
* 'delete' is the same as 'retire'
* 'inventory' is update of extended and/or auxilliary information
  (ext/aux field)
    ext             = hash                  ; Additional extended information.

    ; A list of name/value pairs
    hash            = hash-count *( hash-name hash-value )
    hash-count      = number-4
    hash-value      = longstr
    hash-name       = string

    ; Strings are always length + text contents
    string          = number-1 *VCHAR
    longstr         = number-4 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-4        = 4OCTET
    number-8        = 8OCTET
